name: iOS/macOS CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: macos-14
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Select Xcode Version
        run: sudo xcode-select -s /Applications/Xcode_16.2.app/Contents/Developer

      - name: Install xcbeautify
        run: |
          brew install xcbeautify

      - name: Show Available Schemes (Debugging Step)
        run: xcodebuild -project EssentialFeed/EssentialFeed.xcodeproj -list

      - name: Build & Test CI_macOS
        run: |
          xcodebuild clean build test \
            -project EssentialFeed/EssentialFeed.xcodeproj \
            -scheme "CI_macOS" \
            CODE_SIGN_IDENTITY="" CODE_SIGNING_REQUIRED=NO \
            -sdk macosx \
            -destination "platform=macOS" \
            ONLY_ACTIVE_ARCH=YES | xcbeautify

      - name: Build & Test CI_iOS
        run: |
          xcodebuild clean build test \
            -project EssentialFeed/EssentialFeed.xcodeproj \
            -scheme "CI_iOS" \
            CODE_SIGN_IDENTITY="" CODE_SIGNING_REQUIRED=NO \
            -sdk iphonesimulator \
            -destination "platform=iOS Simulator,OS=18.2,name=iPhone 16" \
            ONLY_ACTIVE_ARCH=YES | xcbeautify

